# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e08f9c59e9ce900462b1cbc09370fac1a6e8e3cba49bb525de5d3396f1011751416ad61f656843ac64f443ffb8f965c8e20be0d3e8ec230e462a56aef24acc4

test:
  secret_key_base: 6795333a84e7e3064d03ccb58c4aefe732d01920fe866f361a7e72fdb6acd4e9a5287994321d51fe6985836c6f815544e883aa4688893b47cf644ab18fe2baf1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
